// src/components/Nav.tsx
import React from 'react'
import Link from 'next/link'
import styled from 'styled-components'

import { NavItem } from '../data/navItems'

const NavList = styled.ul`
  display: flex;
  flex-direction: column;
  font-family: BebasNeueRegular;
  font-size: 2em;
  margin-top: 1em;
`

const NavListItem = styled.li`
  display: flex;
  flex: none;
  justify-content: flex-end;

  @media screen and (max-width: 740px) {
    justify-content: center;
  }
`

const NavListItemLink = styled(Link)`
  &,
  &:visited {
    text-decoration: none;
    color: #000;
  }
`

type Props = {
  items: NavItem[]
}

export const Nav: React.FunctionComponent<Props> = (props) => (
  <NavList>
    {props.items.map((props, i) => (
      <NavListItem key={i}>
        <NavAnchor {...props} />
      </NavListItem>
    ))}
  </NavList>
)

const NavAnchor: React.FunctionComponent<NavItem> = (props) => {
  if (props.external) {
    return (
      <a href={props.href} target="_blank" rel="noopener noreferrer">
        {props.title}
      </a>
    )
  }
  return <NavListItemLink href={props.href}>{props.title}</NavListItemLink>
}

// src/lib/components/Nav.svelte
<script>
	import { resolve } from '$app/paths';
</script>

<ul>
	<li><a href={resolve('/about')}>About</a></li>
	<li><a href={resolve('/releases')}>Releases</a></li>
	<li><a href={resolve('/media')}>Media</a></li>
	<li>
		<a href="mailto:contact@alexesp.co.uk" target="_blank" rel="noopener noreferrer">Contact</a>
	</li>
</ul>

<style>
	ul {
		display: flex;
		flex-direction: column;
		font-family: BebasNeueRegular;
		font-size: 2em;
		margin-top: 1em;
	}

	li {
		display: flex;
		flex: none;
		justify-content: flex-end;
	}

	a,
	a:visited {
		text-decoration: none;
		color: #000;
	}

	@media screen and (max-width: 740px) {
		li {
			justify-content: center;
		}
	}
</style>
